Algoritmo "Ex0"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 13/08/2024
Var
       num1,num2, resultado: real


Inicio
      escreval("Digite um número: ")
      leia(num1,num2)
      resultado <- (num1+num2)*0.45
      escreva("45% da soma dos dois numeros resulta em ",resultado)


Fimalgoritmo