Algoritmo "Ex0"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 13/08/2024
Var
       num1,num2: inteiro


Inicio
      escreval("Digite dois números: ")
      leia(num1,num2)

      escreva(num1," - ",num2," = ",num1-num2)


Fimalgoritmo