Algoritmo "Ex09"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Faz a leitura de três números e calcula a fórmula D = A + C - B
// Autor(a)    : Samuel Fuentes Michels
// Data atual  : 13/08/2024
Var
       a,b,c: inteiro


Inicio
      escreval("Digite os valore de A, B e C : ")
      leia(a,b,c)

      escreva("D = ",a+c-b)


Fimalgoritmo
