Algoritmo "Ex10"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : O programa faz a leitura de três números e calcula a fórmula Z = (L+A*2)/c
// Autor(a)    : Samuel Fuentes Michels
// Data atual  : 13/08/2024
Var
       a,l,c: inteiro


Inicio
      escreval("Digite os valore de A, L e C : ")
      leia(a,l,c)

      escreva("Z = ",(l+a*2)/c)


Fimalgoritmo
